import React, { useState } from "react";
import { LayoutDashboard, MessageSquare, Phone, Workflow, PlugZap, Webhook, Activity, Search, Send, Play, CheckCircle2, ChevronRight, Menu, X, Radio, Plus, Square, RefreshCw, Copy, Check, PhoneCall, PhoneOff, Bot, Database, Zap } from "lucide-react";

const nav = [["Overview",LayoutDashboard],["SMS Inbox",MessageSquare],["Voice",Phone],["AI Workflows",Workflow],["Integrations",PlugZap],["Webhooks",Webhook],["Monitoring",Activity]];

function Button({children,className="",onClick,disabled=false}){return <button className={"primary "+className} onClick={onClick} disabled={disabled}>{children}</button>}

function Overview(){
 const[running,setRunning]=useState(false);const[events,setEvents]=useState([["Inbound SMS received","+1 415 555 0198","2m"],["AI workflow completed","Lead qualification","8m"],["Voice call connected","Support queue","14m"],["CRM contact synced","Salesforce","21m"],["Webhook delivered","delivery.events","32m"]]);
 const runDemo=()=>{setRunning(true);setTimeout(()=>{setEvents(e=>[["Demo workflow completed","SMS → AI → CRM","now"],...e].slice(0,5));setRunning(false)},900)};
 return <><section className="hero"><div><span className="tag">LIVE DEMONSTRATION</span><h2>One platform for every customer conversation.</h2><p>Explore each communication capability as an independent module. Every demo action runs locally in the browser with no paid API dependency.</p><div className="hero-actions"><Button onClick={runDemo} disabled={running}>{running?<><RefreshCw size={16} className="spin"/> Running...</>:<><Play size={16}/> Run demo workflow</>}</Button><button className="secondary" onClick={()=>navigator.clipboard?.writeText("GET /api/messages\nPOST /api/calls\nPOST /api/workflows")}>Copy API examples <Copy size={15}/></button></div></div><div className="orbit"><div className="orbit-ring"></div><div className="core"><Radio size={28}/><span>CC</span></div><div className="node n1">SMS</div><div className="node n2">VOICE</div><div className="node n3">AI</div><div className="node n4">CRM</div></div></section>
 <section className="stats">{[["Messages","18,429","+12.8%"],["Calls","4,281","+8.4%"],["Workflows","126","+18.1%"],["Delivery","99.97%","+0.04%"]].map(s=><div className="stat" key={s[0]}><span>{s[0]}</span><strong>{s[1]}</strong><small>{s[2]} this month</small></div>)}</section>
 <section className="grid"><div className="panel"><div className="panel-head"><div><h3>Recent activity</h3><p>Local demo event stream</p></div><button onClick={()=>setEvents([])}>Clear</button></div><div className="activity">{events.length?events.map((x,i)=><div className="row" key={i}><div className="icon"><CheckCircle2 size={17}/></div><div><b>{x[0]}</b><span>{x[1]}</span></div><time>{x[2]}</time></div>):<div className="empty">No events. Run the demo workflow.</div>}</div></div><div className="panel"><div className="panel-head"><div><h3>Reliability</h3><p>Local simulated metrics</p></div><span className="status"><i/> Healthy</span></div><div className="chart"><div className="bars">{Array.from({length:28},(_,i)=><span style={{height:(28+((i*17)%52))+"%"}} key={i}></span>)}</div><div className="chartlabels"><span>12 AM</span><span>6 AM</span><span>12 PM</span><span>6 PM</span><span>Now</span></div></div><div className="latency"><span>Avg. latency</span><b>184ms</b><span>p95 421ms</span></div></div></section></>
}

function SmsInbox(){
 const[messages,setMessages]=useState([{id:1,from:"+1 415 555 0198",text:"Hi, I need help with my account.",time:"10:42 AM",read:false},{id:2,from:"+1 202 555 0131",text:"Can someone call me back?",time:"10:31 AM",read:true},{id:3,from:"+1 646 555 0177",text:"Thanks, that worked!",time:"9:58 AM",read:true}]);const[selected,setSelected]=useState(1);const[draft,setDraft]=useState("");const current=messages.find(m=>m.id===selected)||messages[0];
 const send=()=>{if(!draft.trim())return;setMessages(m=>[...m,{id:Date.now(),from:"You",text:draft,time:"Now",read:true}]);setDraft("")};
 return <section className="panel module"><div className="module-head"><div><h3>SMS Inbox</h3><p>Independent two-way messaging simulator</p></div><Button onClick={()=>setMessages(m=>[...m,{id:Date.now(),from:"+1 800 555 0100",text:"New demo message received.",time:"Now",read:false}])}><Plus size={15}/> New message</Button></div><div className="sms-layout"><div className="conversation-list">{messages.map(m=><button className={selected===m.id?"conversation selected":"conversation"} onClick={()=>{setSelected(m.id);setMessages(xs=>xs.map(x=>x.id===m.id?{...x,read:true}:x))}} key={m.id}><b>{m.from}</b><span>{m.text}</span><small>{m.time}{!m.read&&<i/>}</small></button>)}</div><div className="chat"><div className="chat-head"><div className="avatar">CC</div><div><b>{current?.from}</b><span>SMS channel · simulated</span></div></div><div className="chat-body"><div className="bubble incoming">{current?.text}</div><div className="bubble outgoing">This is an independent demo response.</div></div><div className="composer"><input value={draft} onChange={e=>setDraft(e.target.value)} onKeyDown={e=>e.key==="Enter"&&send()} placeholder="Type a message..."/><Button onClick={send}><Send size={15}/> Send</Button></div></div></div></section>
}

function Voice(){
 const[call,setCall]=useState("idle");const[number,setNumber]=useState("+1 415 555 0198");const[seconds,setSeconds]=useState(0);
 React.useEffect(()=>{if(call!=="connected")return;const t=setInterval(()=>setSeconds(s=>s+1),1000);return()=>clearInterval(t)},[call]);
 const start=()=>{setCall("connecting");setSeconds(0);setTimeout(()=>setCall("connected"),700)};const fmt="00:"+String(Math.floor(seconds/60)).padStart(2,"0")+":"+String(seconds%60).padStart(2,"0");
 return <section className="panel module"><div className="module-head"><div><h3>Voice Console</h3><p>Independent call-control simulator</p></div><span className={call==="connected"?"status":"status muted"}><i/> {call==="connected"?"Connected":call==="connecting"?"Connecting":"Ready"}</span></div><div className="voice-console"><div className="call-orb"><PhoneCall size={34}/></div><h2>{number}</h2><p>{call==="connected"?fmt:"Outbound voice session"}</p><div className="number-row"><input value={number} onChange={e=>setNumber(e.target.value)}/></div><div className="call-controls">{call==="connected"?<Button onClick={()=>setCall("idle")}><PhoneOff size={16}/> End call</Button>:<Button onClick={start}><Phone size={16}/> Start call</Button>}<button className="secondary" onClick={()=>{setCall("idle");setSeconds(0)}}><Square size={14}/> Reset</button></div><div className="technical-strip"><span>Codec <b>Opus</b></span><span>Jitter <b>12ms</b></span><span>Packet loss <b>0.01%</b></span></div></div></section>
}

function AIWorkflows(){
 const[running,setRunning]=useState(false);const[done,setDone]=useState(false);const run=()=>{setRunning(true);setDone(false);setTimeout(()=>{setRunning(false);setDone(true)},1200)};
 const steps=[["Receive message",MessageSquare],["Classify intent",Bot],["Apply business rule",Zap],["Create CRM record",Database]];
 return <section className="panel module"><div className="module-head"><div><h3>AI Workflow Builder</h3><p>Independent local workflow execution</p></div><Button onClick={run} disabled={running}>{running?<><RefreshCw size={15} className="spin"/> Running</>:<><Play size={15}/> Run workflow</>}</Button></div><div className="workflow"><div className="workflow-trigger">Trigger: <b>Inbound SMS</b></div>{steps.map(([label,Icon],i)=><React.Fragment key={label}><div className={running&&i===1?"workflow-step active":"workflow-step"}><Icon size={18}/><div><b>{label}</b><span>{i===0?"Event received":i===1?"AI decision layer":i===2?"Rules evaluated":"Record prepared"}</span></div>{(done||i===0)&&<Check size={17}/>}</div>{i<steps.length-1&&<div className="connector"/>}</React.Fragment>)}{done&&<div className="success-box"><CheckCircle2 size={17}/> Workflow completed locally in 1.2s</div>}</div></section>
}

function Integrations(){
 const[connected,setConnected]=useState({});const items=[["CRM / Salesforce","Sync contacts and opportunities"],["PMS / Property System","Route property conversations"],["EHR / Healthcare","Connect patient communication flows"],["Custom REST API","Connect any HTTP service"]];
 return <section className="panel module"><div className="module-head"><div><h3>Integrations</h3><p>Each connector can be tested independently</p></div></div><div className="integration-grid">{items.map(([name,desc])=><div className="integration" key={name}><div className="integration-icon"><PlugZap size={18}/></div><b>{name}</b><span>{desc}</span><button onClick={()=>setConnected(c=>({...c,[name]:!c[name]}))}>{connected[name]?"Connected · Disconnect":"Connect demo"} <ChevronRight size={14}/></button></div>)}</div></section>
}

function Webhooks(){
 const[logs,setLogs]=useState([]);const[copied,setCopied]=useState(false);const fire=()=>setLogs(l=>[{id:Date.now(),event:"message.delivered",status:200,time:new Date().toLocaleTimeString()},...l].slice(0,6));const copy=()=>{navigator.clipboard?.writeText(JSON.stringify({event:"message.delivered",id:"evt_demo_001",status:"delivered"},null,2));setCopied(true);setTimeout(()=>setCopied(false),1200)};
 return <section className="panel module"><div className="module-head"><div><h3>Webhook Delivery</h3><p>Independent event delivery simulator</p></div><Button onClick={fire}><Send size={15}/> Send test event</Button></div><div className="webhook-grid"><div className="codebox"><div className="codehead"><span>POST /webhooks/events</span><button onClick={copy}>{copied?<Check size={14}/>:<Copy size={14}/>}</button></div><pre>{JSON.stringify({event:"message.delivered",id:"evt_demo_001",status:"delivered"},null,2)}</pre></div><div className="delivery-list">{logs.length?logs.map(x=><div className="delivery" key={x.id}><CheckCircle2 size={16}/><div><b>{x.event}</b><span>HTTP {x.status} · {x.time}</span></div></div>):<div className="empty">No delivery events yet. Send a test event.</div>}</div></div></section>
}

function Monitoring(){
 const[refreshed,setRefreshed]=useState(0);return <section className="panel module"><div className="module-head"><div><h3>Monitoring</h3><p>Independent simulated platform health view</p></div><Button onClick={()=>setRefreshed(x=>x+1)}><RefreshCw size={15}/> Refresh</Button></div><div className="monitor-grid">{[["API availability","99.99%","Healthy"],["Message delivery","99.97%","Healthy"],["Voice latency","184ms","Normal"],["Webhook queue","0 pending","Healthy"],["AI workflow runtime","1.2s","Normal"],["Event throughput","842/min","Healthy"]].map(x=><div className="metric" key={x[0]}><span>{x[0]}</span><strong>{x[1]}</strong><small><i/> {x[2]}</small></div>)}</div><div className="refresh-note">Last refreshed locally · update #{refreshed}</div></section>
}

function App(){
 const[active,setActive]=useState("Overview");const[mobile,setMobile]=useState(false);const[query,setQuery]=useState("");
 const pages={Overview:<Overview/>,"SMS Inbox":<SmsInbox/>,Voice:<Voice/>,"AI Workflows":<AIWorkflows/>,Integrations:<Integrations/>,Webhooks:<Webhooks/>,Monitoring:<Monitoring/>};
 return <div className="app"><aside className={mobile?"sidebar open":"sidebar"}><div className="brand"><div className="brandmark"><Radio size={19}/></div><div><b>CloudConnect</b><span>Communications</span></div><button className="close" onClick={()=>setMobile(false)}><X/></button></div><nav>{nav.map(([name,Icon])=><button className={active===name?"nav active":"nav"} onClick={()=>{setActive(name);setMobile(false)}} key={name}><Icon size={18}/><span>{name}</span>{name==="SMS Inbox"&&<em>7</em>}</button>)}</nav><div className="sidecard"><div className="pulse"></div><div><b>All systems operational</b><small>99.97% simulated uptime</small></div></div></aside><main><header><div className="title-row"><button className="hamb" onClick={()=>setMobile(true)}><Menu/></button><div><p className="eyebrow">COMMUNICATIONS PLATFORM</p><h1>{active}</h1></div></div><div className="header-actions"><div className="search"><Search size={16}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search this module"/></div><div className="avatar">TE</div></div></header>{pages[active]}<footer>Independent technical demonstration · All interactions are local demo simulations · Not affiliated with Mango Voice or any communications provider.</footer></main></div>
}
export default App;